### ISSUE TITLE
请求加入 BIThesis 项目到 GuideLinks 中。

### ISSUE THREAD

**Issue by fky2015** [BITNP/bitnp-website#1]
- 项目地址：https://github.com/BITNP/BIThesis 或 https://bithesis.bitnp.net
- 内容介绍：北京理工大学非官方 LaTeX 模板集合，包含本科、研究生毕业设计模板及更多。
- Logo: https://github.com/BITNP/BIThesis/blob/main/assets/bithesis_icon.svg

**Comment by fky2015** [comment]
如果可以的话，不妨也加一份到 Related Links。

我可以完成这份 PR，如果另有人想完成的话，可以在右侧 Assignees 中认领一下以免冲突。

**Comment by taitanium** [comment]
Push 上去啦已经（，图标用的Guide里同一套的，看看这样还行不（￣︶￣）↗　
<img width="266" alt="image" src="https://user-images.githubusercontent.com/43071125/192126266-be3f2483-137e-4580-a68b-e963bda17039.png">
