### ISSUE TITLE
建议router不用hash模式，避免URL中的"#"

### ISSUE THREAD

**Issue by wormtql** [BITNP/bitnp-website#2]

**Comment by everything411** [comment]
由于网协主页托管不在自己的服务器上，无法控制HTTP服务器的行为，因此为方便部署使用了hash模式。

**Comment by phy25** [comment]
其实关系不是很大：https://stackoverflow.com/questions/63985225/server-configuration-for-vue-js-history-mode-with-vercel

然而理想情况应该是每个页面都静态化了。

**Comment by everything411** [comment]
vercel确实支持修改服务器行为，但是我们还有一个github pages的备份没法用history模式，以及还要考虑未来可能转移到其他的托管服务商，所以目前还是暂时保留hash模式。
