### ISSUE TITLE
页脚图标错误

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/bitnp-website#3]
[cover3.png](https://github.com/BITNP/bitnp-website/blob/d69f96adb54603d2ac20ba0ea3be901e8541f29f/src/assets/cover3.png) 是旧图标，[icon.png](https://github.com/BITNP/bitnp-website/blob/d69f96adb54603d2ac20ba0ea3be901e8541f29f/src/assets/ico.png) 是新的。

不过为什么有俩呢？

**Comment by taitanium** [comment]
以为都是来着（），老的好像是从老的bitnp.net的轮播图里抠出来的（x

**Comment by YDX-2147483647** [comment]
Z□□准备面试幻灯片时也是这么想的，从此时不时被鞭尸。

**Comment by taitanium** [comment]
hhhhhh，已更正在新的commit里
