### ISSUE TITLE
使用github action自动部署

### ISSUE THREAD

**Issue by everything411** [BITNP/bitnp-website#5]
考虑使用github action自动部署至github pages

**Comment by flwfdd** [comment]
国内访问可能还是不够稳定（
既然有备案就还是利用一下
不过之后或许确实可以在服务器上加个自动部署的脚本

**Comment by everything411** [comment]
可以用作开发，跟随master自动部署

**Comment by everything411** [comment]
deploy to github pages at https://bitnp.github.io with a fork of this repo at https://github.com/BITNP/bitnp.github.io
